### ISSUE TITLE
Error presenting challenge: the server is currently unable to handle the request

### ISSUE THREAD

**Issue by maaroen** [robbietjuh/cert-manager-webhook-transip#8]
Hello Robbie,

Do you have any idea what causes this error: Error presenting challenge: the server is currently unable to handle the request (post transip.cert-manager.webhook.transip)

This makes me unable to do the dns challenge.

**Comment by gboor** [comment]
I just ran into this as well and the log for the webhook itself is full of;

http: TLS handshake error from 10.164.0.61:34096: remote error: tls: bad certificate

With a whole range of internal service IPs.

I have no idea what this means or why this is happening, but this indeed does not work.

**Comment by maaroen** [comment]
Hey @gboor,

Mine is working now, I made a few changes to the code and configuration. You can see the code changes in the fork I made from this repo. If with this is still doesn't work I'll send an example of my configuration.

**Comment by gboor** [comment]
Excellent news! I'll give it a spin sometime over the weekend or early next week and will let you know :)

**Comment by gboor** [comment]
@maaroen since there are no amd64 docker images built in your version, I tried to build it myself, but run into the following issues;

```
.\main.go:99:27: cannot use ch.Config (type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1".JSON) as type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".JSON in argument to loadConfig
.\main.go:147:27: cannot use ch.Config (type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1".JSON) as type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".JSON in argument to loadConfig
```

I'm just dumping this here in case you know a quick fix. If not, I'll spend some more time on it later this week. Seems like it should be fairly simple to resolve, I just don't have the time right now.

**Comment by maaroen** [comment]
@gboor There should be an amd64 docker image available now ;)

**Comment by maaroen** [comment]
@gboor I pushed the latest source I had left on my pc, seems I missed some changes I made in the repo there.
The dockerhub version might work now, I'm not able to test it atm, because after pulling the changes I get the same errors as you get. 

Try if it works, if not I'll try to solve it later.

**Comment by gboor** [comment]
I was indeed able to deploy it now, thanks for the quick follow-up :)

Running into some permission issues now;

```
cert-manager/controller/challenges "msg"="re-queuing item due to error processing" "error"="transip.certmanager.webhook.transip is forbidden: User \"system:serviceaccount:cert-manager:cert-manager\" cannot create resource \"transip\" in API group \"certmanager.webhook.transip\" at the cluster scope" "key"="backend-test/tls-survey-backend-mq95v-2093192934-2671809839"
```

I'm pretty sure that's a different issue, though. Maybe I need to mess around with the cert-manager deployment and change the RBAC settings. Will let you know if it works once I manage to sort this issue!

**Comment by maaroen** [comment]
@gboor I fixed the issue in the repo. and uploaded a new version, could you try this one? I've had this issue also, it might be fixed with this new version.

**Comment by gboor** [comment]
Thansk for the quick follow-up again. It deployed just fine and I set the pullPolicy to Always to make sure it updated the container, but the same problem still persists. I think that's not an issue that can be solved in code, but really an RBAC issue.

**Comment by maaroen** [comment]
@gboor How do you deploy the webhook?
I now remember that I depoy it like this:
- kubectl create namespace cert-manager
- helm repo add jetstack https://charts.jetstack.io
- helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.0.4 --set installCRDs=true --set rbac.create=false


- git clone git@github.com:maaroen/cert-manager-webhook-transip.git
- cd cert-manager-webhook-transip
- helm install cert-manager-webhook-transip --namespace=cert-manager ./deploy/transip-webhook

Notice the --set installCRDs=true, I think that might help you.

**Comment by gboor** [comment]
It's working now! Turns out I had a typo in the groupName field in the issuer... so it could not find the correct api group and threw a permission issue.

Thanks a lot for all the suggestions and feedback!

**Comment by maaroen** [comment]
Glad I could be of help @gboor! I've had exactly the same issue, this error was super familiar haha.

you have the DNS challenges working now?

Veel plezier met je certs!

**Comment by gboor** [comment]
DNS challenger are working and I can get wildcard certs (which was the whole point), so very happy here :)

Helemaal goed zo! Bedankt!

**Comment by maaroen** [comment]
Ah yea, I also did it for wildcard certs, is so nice to see it finally working.
I guess I'll be closing this issue since it works now.
